#include "src/Unit/Vampire.h"
#include "src/State/SoldierState.h"
#include "src/Unit/Werewolf.h"
#include "src/Unit/Rogue.h"
#include "src/Spellcaster/Wizard.h"
#include "src/Spell/Cruciatus.h"
#include "src/Spell/AvadaKedavra.h"
